version: "3.5"

services:
  api_01: &api
    image: rinha
    hostname: api_01
    container_name: api_01
    environment:
      - PORT=3000
      - POSTGRES_DATABASE=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  api_02:
    <<: *api
    hostname: api_02
    container_name: api_02
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_01
      - api_02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/migrations
      - ./migrations:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 10
